apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-echoserver
  template:
    metadata:
      labels:
        app: istio-echoserver
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.0
        imagePullPolicy: Always
        name: istio-echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: istio-echoserver
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: istio-echoserver
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-echoserver
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-echoserver
spec:
  hosts:
  - "*"
  gateways:
  - istio-echoserver
  http:
  - match:
    - uri:
        prefix: /http-echo
    route:
    - destination:
        host: istio-echoserver
        port:
          number: 80
